### ISSUE TITLE
Debian dependencies

### ISSUE THREAD

**Issue by setop** [danhper/asdf-python#175]
### Provide environment information

```
OS:
Linux REDACTED 5.10.0-9-686-pae #1 SMP Debian 5.10.70-1 (2021-09-30) i686 GNU/Linux

SHELL:
GNU bash, version 5.1.4(1)-release (i686-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

BASH VERSION:
5.1.4(1)-release

ASDF VERSION:
v0.13.1-0586b37

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/home/REDACTED/.asdf
ASDF_DIR=/home/REDACTED/.asdf
ASDF_CONFIG_FILE=/home/REDACTED/.asdfrc

ASDF INSTALLED PLUGINS:
python                       https://github.com/danhper/asdf-python.git master 5e277e2
```

### To Reproduce

`asdf install python 3.11.5`

### Describe the Bug

```
Installing Python-3.11.5...


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/REDACTED/.asdf/installs/python/3.11.5/lib/python3.11/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/REDACTED/.asdf/installs/python/3.11.5/lib/python3.11/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/REDACTED/.asdf/installs/python/3.11.5/lib/python3.11/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
WARNING: The Python ctypes extension was not compiled. Missing the libffi lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/REDACTED/.asdf/installs/python/3.11.5/lib/python3.11/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named '_ssl'
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Debian 11 using python-build 2.3.27-5-gf7f09650)

```

### Expected Behaviour

Installed Python-3.11.5 to /home/REDACTED/.asdf/installs/python/3.11.5

I had to perform `sudo apt-get install libssl-dev libffi-dev libbz2-dev libncurses-dev libreadline-dev libsqlite3-dev liblzma-dev` in order to fix this issue. **These system dependencies should be listed in the README**.

**Comment by krzysztofjeziorny** [comment]
Now [they are](https://github.com/pyenv/pyenv/wiki#suggested-build-environment).
